### ISSUE TITLE
[crx] FSWatcher monitoring entire C: drive for changes

### ISSUE THREAD

**Issue by vinayakkuradia** [guocaoyi/create-chrome-ext#27]
The server gets terminated when tries to access C: drive windows protected files such as "C:\DumpStack.log.tmp" and hibernate file.

```
> vite


  vite v2.9.15 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 649ms.

9:48:30 AM [crx] files start ../../../../../../../build/v0.9.0
The emitted file "icons/icon_gradient_inactive_x16.png" overwrites a previously emitted file of the same name.
The emitted file "icons/icon_gradient_inactive_x48.png" overwrites a previously emitted file of the same name.
The emitted file "icons/icon_gradient_inactive_x32.png" overwrites a previously emitted file of the same name.
The emitted file "icons/icon_gradient_inactive_x128.png" overwrites a previously emitted file of the same name.
9:48:30 AM [crx] files ready in 282ms
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///C:/dir1/dir2/dir3/dir4/dir5/extension/node_modules/rollup/dist/es/shared/watch.js:4397:10)
    at NodeFsHandler$1._boundHandleError (file:///C:/dir1/dir2/dir3/dir4/dir5/extension/node_modules/rollup/dist/es/shared/watch.js:2873:43)
    at ReaddirpStream.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'lstat',
  path: 'C:\\DumpStack.log.tmp'
}
Node.js v18.16.0
```

**Comment by vinayakkuradia** [comment]
Dependencies: 
```
"dependencies": {
    "preact": "^10.8.2"
  },
  "devDependencies": {
    "@crxjs/vite-plugin": "^1.0.12",
    "@preact/preset-vite": "^2.3.0",
    "autoprefixer": "^10.4.14",
    "postcss": "^8.4.23",
    "prettier": "^2.7.1",
    "tailwindcss": "^3.3.1",
    "vite": "^2.9.13"
  }
```

**Comment by markarenin** [comment]
Hi! Did you fixed that? I've got the same problem

**Comment by vinayakkuradia** [comment]
Hello @markarenin, No, I stopped using it. I now use [crxjs](https://github.com/crxjs/chrome-extension-tools).

**Comment by guocaoyi** [comment]
> Hello @markarenin, No, I stopped using it. I now use [crxjs](https://github.com/crxjs/chrome-extension-tools).

create-chrome-ext just a boilerplate, it's depends crxjs@2.x beta

**Comment by markarenin** [comment]
> > Hello @markarenin, No, I stopped using it. I now use [crxjs](https://github.com/crxjs/chrome-extension-tools).
> 
> create-chrome-ext just a boilerplate, it's depends [crxjs@2.x](mailto:crxjs@2.x) beta

Okay. Thank you 💚
