### ISSUE TITLE
Cannot access extension pages, vite build also not working

### ISSUE THREAD

**Issue by AqueelAhmedV** [guocaoyi/create-chrome-ext#98]
Issue started after updating to Chrome 130.0.6723.70 (Windows), 
extension pages like sidepanel.html, and popup.html show ERR_FILE_NOT_FOUND in development mode (`yarn dev`)

`yarn build` shows the following error:
```shell
yarn run v1.22.21
$ vite build
vite v4.5.1 building for production...
✓ 13 modules transformed.
✓ built in 136ms
[vite:html-inline-proxy] Could not load C:UsersaqueeDocumentscodedevcrx     imeline.html?html-proxy&inline-css&index=0.css (imported by timeline.html): No matching HTML proxy module found from C:UsersaqueeDocumentscodedevcrx      imeline.html?html-proxy&inline-css&index=0.css 
error during build:
Error: Could not load C:UsersaqueeDocumentscodedevcrx       imeline.html?html-proxy&inline-css&index=0.css (imported by timeline.html): No matching HTML proxy module found from C:UsersaqueeDocumentscodedevcrx       imeline.html?html-proxy&inline-css&index=0.css
    at Object.load (file:///C:/Users/aquee/Documents/code/dev/crx/node_modules/vite/dist/node/chunks/dep-68d1a114.js:37403:27)
    at file:///C:/Users/aquee/Documents/code/dev/crx/node_modules/rollup/dist/es/shared/node-entry.js:25544:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///C:/Users/aquee/Documents/code/dev/crx/node_modules/rollup/dist/es/shared/node-entry.js:25444:28)
    at async file:///C:/Users/aquee/Documents/code/dev/crx/node_modules/rollup/dist/es/shared/node-entry.js:24611:75
    at async Queue.work (file:///C:/Users/aquee/Documents/code/dev/crx/node_modules/rollup/dist/es/shared/node-entry.js:25654:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sakibul-islam** [comment]
Update the `@crxjs/vite-plugin` package to the latest release:

```bash
yarn add -D @crxjs/vite-plugin@^2.0.0-beta.28
```

It should fix the issue.

**Comment by AqueelAhmedV** [comment]
It worked. Thank you
